spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xapp_schema
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    redis:
      host: localhost
      port: 6379